version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306

  api:
    build:
      context: .
      dockerfile: ${PWD}/.docker/node/Dockerfile
    volumes:
      - node_modules:/home/lendsqr/code/node_modules:rw
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
    command: yarn start

  nginx:
    build:
      context: .
      dockerfile: ${PWD}/.docker/nginx/Dockerfile
    depends_on:
      - api
    expose:
      - 80
      - 443
    env_file:
      - .env
    restart: always

volumes:
  mysql:
  node_modules:


networks:
  default:
    name: webproxy
