version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306

  api:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
    command: yarn start

  nginx:
    build:
      context: .
      dockerfile: ${PWD}/.docker/nginx/Dockerfile
    depends_on:
      - api
    expose:
      - 80
      - 443
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mysql:


networks:
  default:
    name: webproxy
