version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306

  api:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    command: yarn prod

volumes:
  mysql:


networks:
  default:
    name: webproxy
