name: AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_MYSQL_ROOT_USER: ${{ secrets.MYSQL_ROOT_USER }}
          envkey_MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          envkey_MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          envkey_MYSQL_USER: ${{ secrets.MYSQL_USER }}
          envkey_MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          envkey_MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          envkey_MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          envkey_MYSQL_TEST_DATABASE: ${{ secrets.MYSQL_TEST_DATABASE }}
          envkey_API_PORT: ${{ secrets.API_PORT }}

          envkey_LETSENCRYPT_HOST: ${{ secrets.LETSENCRYPT_HOST }}
          envkey_LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
          envkey_VIRTUAL_HOST: ${{ secrets.VIRTUAL_HOST }}

          file_name: .env
          fail_on_empty: false

      - name: Install dependencies
        run: |
          docker-compose build --no-cache --force-rm
          docker-compose up --force-recreate -d

  deploy:
    runs-on: self-hosted
    needs:
      - build

    steps:
      - name: Deploy to AWS
        run: docker-compose run --rm api yarn prod
